### ISSUE TITLE
Using custom version of libctru?

### ISSUE THREAD

**Issue by smartperson** [MarcuzD/TreeHome#1]
I'm looking at compiling the template so far, but it does not link against the libctru build mentioned in Readme.md, [ctrulib#5725ec2dedfffb2ee721dd8cddb3d24c288f452f](https://github.com/smealum/ctrulib/tree/5725ec2dedfffb2ee721dd8cddb3d24c288f452f).

It looks like calls in soos/main.c, specifically to aptSendSyncRequest(), fail when compiling against the above-mentioned libctru. [apt.h](https://github.com/smealum/ctrulib/blob/5725ec2dedfffb2ee721dd8cddb3d24c288f452f/libctru/include/3ds/services/apt.h) does not have the method.

It seems like for long-term template health, we should figure out a way to access the required services, locks, and handles with the vanilla library.

**Comment by MarcuzD** [comment]
Lol, it even says in the README, that the modified ctrulib is INCLUDED in the template! It's even in the Makefile, and the template directory structure itself, clearly visible :stuck_out_tongue: 

https://puu.sh/rpzGC/6e3dfa9114.png
